name: Run lint checks, tests and build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: "actions/checkout@v2"
      - name: Setup JDK 8
        uses: actions/setup-java@2
        with:
          java-version: '8'
          distribution: 'adopt-openj9'
      - name: Run tests
        run: mvn clean verify
      - name: Run build
        uses: mvn package
